name: trains_theme
type: theme
description: Custom Drupal 8 admin theme for Trains demo
base theme: bartik

package: Other
core: 8.x

regions:
  main_nav: Main navigation
  header: Header
  help: Help
  breadcrumbs: Breadcrumbs
  title: Title
  content: Content
  sidebar: Sidebar
  footer: Footer

libraries:
  - train_theme/bootstrap_cdn
  - train_theme/global-styling
  